services:
  api:
    build:
      context: ./api
    environment:
      - AUTH_USER=${AUTH_USER:-username}
      - AUTH_PASS=${AUTH_PASS:-password}
      - PORT=${PORT_API:-8080}
      - OVP_DATA_DIR=${OVP_DATA_DIR:-/srv/docker/ovp}
      - API_CORS_ORIGIN=http://localhost:${PORT_WEB:-5173}
      - NODE_ENV=production
    volumes:
      - ${OVP_DATA_DIR:-/srv/docker/ovp}:${OVP_DATA_DIR:-/srv/docker/ovp}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - default
      - main_proxy

  web:
    build:
      context: ./web
    environment:
      - VITE_API_BASE=/api
      - NODE_ENV=production
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - default
      - main_proxy

networks:
  main_proxy:
    external: true
    name: ${PROXY_NETWORK:-proxy}
