name: Build and Publish Docker Images (manual only)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  API_IMAGE_NAME: ovp-api
  WEB_IMAGE_NAME: ovp-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (API)
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.API_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Extract metadata (WEB)
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.WEB_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Build and push WEB
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
